# Generated by Django 6.0.6 on 2026-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservatoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('tx_waveform', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_waveform', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('station', models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], default=9, null=True)),
                ('event_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('xmit_station', models.CharField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], max_length=100, null=True)),
                ('rcvr_station', models.CharField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], max_length=100, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='ddm_payloads/')),
                ('num_bytes', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(default=0.0)),
            ],
        ),
    ]
