# Generated by Django
from django.db import migrations
from django.contrib.auth.hashers import make_password

def migrate_and_hash_users(apps, schema_editor):
    CustomUser = apps.get_model('ngRadar_Website', 'User')
    AuthUser = apps.get_model('auth', 'User')

    for old_user in CustomUser.objects.all():
        if not AuthUser.objects.filter(username=old_user.username).exists():
            
            hashed_password = make_password(old_user.password)
            
            # Insert cleanly into auth_user
            AuthUser.objects.create(
                username=old_user.username,
                password=hashed_password,
                is_active=True,
                is_staff=False,
                is_superuser=False
            )

def rollback_users(apps, schema_editor):
    # Optional: Deletes the users from auth_user if you ever reverse this migration
    AuthUser = apps.get_model('auth', 'User')
    CustomUser = apps.get_model('ngRadar_Website', 'User')
    usernames = CustomUser.objects.values_list('username', flat=True)
    AuthUser.objects.filter(username__in=usernames).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(migrate_and_hash_users, reverse_code=rollback_users),
    ]
