# Generated by Django 6.0.6 on 2026-07-06 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsocEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('tx_waveform', models.CharField(max_length=100)),
                ('rec_waveform', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('latency_ms', models.FloatField(default=0.0)),
                ('product_type', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=100)),
                ('station', models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], default=9, null=True)),
                ('created_at', models.DateTimeField()),
                ('xmit_station', models.CharField(choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], max_length=100)),
                ('rcvr_station', models.CharField(choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], max_length=100)),
                ('image_file', models.ImageField(upload_to='ddm_payloads/')),
                ('num_bytes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gbtEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('tx_waveform', models.CharField(max_length=100)),
                ('rec_waveform', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('latency_ms', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='uiEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_waveform', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
            ],
        ),
    ]
