# Generated by Django 5.2.16 on 2026-07-09 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0002_dsocevent_gbtevent_uievent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsocevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='rcvr_station',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='rec_waveform',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='station',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='tx_waveform',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='xmit_station',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='image_file',
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="observatoryevent",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True), # Changed unique=True to null=True
        ),
    ]
