# Generated by Django 6.0.6 on 2026-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0002_auto_20260625_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='observatoryevent',
            old_name='obs_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='rec_waveform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='tx_waveform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='num_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)')], default=9, null=True),
        ),
    ]
