# Generated by Django 5.2.16 on 2026-07-09 13:32
import uuid
from django.db import migrations

def gen_unique_uuids(apps, schema_editor):
    ObservatoryEvent = apps.get_model("ngRadar_Website", "ObservatoryEvent")
    for row in ObservatoryEvent.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0003_remove_dsocevent_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_unique_uuids, reverse_code=migrations.RunPython.noop),
    ]
