# Generated by Django 5.2.16 on 2026-07-09 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0004_auto_20260709_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name="observatoryevent",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
    ]
