# Generated by Django 5.2.16 on 2026-07-09 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0005_auto_20260709_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsocevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='rcvr_station',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='rec_waveform',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='station',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='tx_waveform',
        ),
        migrations.RemoveField(
            model_name='dsocevent',
            name='xmit_station',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='image_file',
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='rcvr_station',
            field=models.CharField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Deep Space Optical Communications)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Deep Space Optical Communications)')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='xmit_station',
            field=models.CharField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Deep Space Optical Communications)')], max_length=100, null=True),
        ),
    ]
