# Generated by Django 5.2.16 on 2026-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0006_remove_dsocevent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsocevent',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='observatoryevent',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='image_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
