# Generated by Django 5.2.16 on 2026-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0007_remove_dsocevent_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observatoryevent',
            name='rcvr_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)')], null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='xmit_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)')], null=True),
        ),
    ]
