# Generated by Django 5.2.16 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0008_alter_observatoryevent_rcvr_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngrok_endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootstrap', models.CharField()),
            ],
        ),
    ]
