# ===========================================================================
# We use 1 Dockerfile and 1 docker-compose.yml file to build and 
# run the Django application in a containerized environment.
# If hosted locallly, it uses the local Postgres database. If in production, 
# it uses the Render-hosted Postgres database.
# ===========================================================================

services:
  ngradar_website:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - .:/service
    ports:
      - 8000:8000
    networks:
      - ngradar_website_network
    stdin_open: true
    tty: true

  postgres:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ngradar_website
      - POSTGRES_PASSWORD=ngradar_website
      - POSTGRES_DB=localdev
    networks:
      - ngradar_website_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ngradar_website -d localdev"]
      interval: 5s
      timeout: 5s
      retries: 5

  staging_loader:
    build:
      context: .
      dockerfile: load-staging-data.Dockerfile
    env_file:
      - .env
    networks:
      - ngradar_website_network
    depends_on:
      - postgres
    volumes:
      - staging_dump:/dump
    profiles:
      - tools

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    profiles: ["kafka"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ngradar_website_network

  broker:
    image: confluentinc/cp-kafka:7.5.1
    profiles: ["kafka"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ngradar_website_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    profiles: ["kafka"]
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      - broker
    networks:
      - ngradar_website_network

  ngrok:
    image: ngrok/ngrok:latest
    profiles: ["ngrok"]
    command: tcp broker:29092 --log stdout --authtoken ${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040"
    networks:
      - ngradar_website_network

  worker:
    build: .
    command: python manage.py consumer
    volumes:
      - .:/service
    networks:
      - ngradar_website_network
    profiles:
      - kafka


  seaweedfs:
    build: .
    ports:
      - "9333:9333"
      - "8080:8080"
      - "8333:8333"
    volumes:
      - seaweed_data:/data
    networks:
      - ngradar_website_network
    env_file:
      - .env


volumes:
  postgres_data:
  staging_dump:
  seaweed_data:

networks:
  ngradar_website_network:
    driver: bridge