services:
  
  kafka:
    image: apache/kafka:3.7.0
    container_name: local_kafka
    ports:
      - "9092:9092"   # Traffic inside the internal Docker Network
      - "9094:9094"   # Traffic from outside via ngrok
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://0.tcp.ngrok.io:13911' #on work station, after authenticating ngrok token, ngrok tcp 9094 to get ngrok host:port to paste into EXTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_dashboard
    ports:
      - "8080:8080" # Open http://localhost:8080 in web browser to access the Kafka UI
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    depends_on:
      - kafka

  local-postgres:
    image: postgres:16-alpine
    container_name: local_postgres
    ports:
      - "5432:5432" # Exposed to PC for DBeaver (Database Management Tool similar to pgAdmin)
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mylocaldb

  django-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_consumer
    command: python manage.py run_consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DATABASE_URL=postgres://myuser:mypassword@local-postgres:5432/mylocaldb # What should this be?
    depends_on:
      - kafka
      - local-postgres
