"""
Django settings for prototype_project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
DEBUG = os.environ.get('DJANGO_DEBUG')

# Allow local Docker containers AND Render's domain depending on environment
# Have not tested this yet
ALLOWED_HOSTS = [
    host.strip() 
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ngRadar_Website',
]

MIDDLEWARE = [
    # the order of these is VERY important. 
    # if making changes, ensure the order is correct
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'login_required.middleware.LoginRequiredMiddleware',
    'ngRadar_Website.robots.RobotsMiddleware', 
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher', 
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'wsgi.application'

# This will allow for easy switching between local and demo databases without changing the code.
# When local, it will use the local Postgres database from our non-commited .env file. 
# When our code base is deployed on the cloud, and since we don't commit our .env file to Github,
# Render will default to the DATABASE_URL that we will configure via the Render dashboard to connect 
# to the Render-hosted Postgres database.
DATABASES = {
    "default": dj_database_url.config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'ngRadar_Website' / 'static',
]


# Authentication
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = 'login'            # name of the login route in urls.py
LOGIN_REDIRECT_URL = 'index'    # after login -> /ngRadar_Website/index.html
LOGOUT_REDIRECT_URL = 'login'  # after logout -> back to the login page

# Let everyone see the login page; LoginRequiredMiddleware guards every other page.
LOGIN_REQUIRED_IGNORE_PATHS = [
    r'^/login/$',
]

# ==============================================================================
# LOCAL WORKSTATION OBJECT STORAGE (ACTIVE FOR PROTOTYPING)
# For prototype purposes only, to be replaved with cloud object storage later
# ==============================================================================
MEDIA_URL = '/media/'
<<<<<<< HEAD
MEDIA_ROOT = BASE_DIR / 'media'
=======
MEDIA_ROOT = BASE_DIR / 'media'

# Setting to for live changing 
# if DEBUG:
#     INSTALLED_APPS += ['livereload']
#     MIDDLEWARE.insert(0, 'livereload.middleware.LiveReloadScript')
>>>>>>> aa0fbb6 (remove livereload and clean extra code index.html)
