# Required connection configs for Kafka consumer
bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=IJSV5X3574J3HYIL
sasl.password=cfltPCJf/xRCQWMNdTL7nU7L8u0+5rRPPs8ndp9Y85vY/G8YMPU96BDw+79mw2nQ

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-1b8cd662-ef1d-45b4-9fe9-8d2cdb69aeff


##############################################

# USE THIS TO MAKE A consumer.properties file

##############################################
