# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=YBHGA5NALJU7SNXL
sasl.password=cfltLfLKAU83bIYY7dcQjtZBfEJBfLjQA8X4Logf9ytmDdq3h5/DcWLNu1JYqyGg

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-consumer-bbff1152-c1d9-41bb-98bd-ee0124646f97
