# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=YBHGA5NALJU7SNXL
sasl.password=cfltLfLKAU83bIYY7dcQjtZBfEJBfLjQA8X4Logf9ytmDdq3h5/DcWLNu1JYqyGg

schema.registry.url=https://<SCHEMA_REGISTRY_URL>

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-producer-4e1ecb53-9c6a-4e56-b269-7dc0a12991e3
